### ISSUE TITLE
[Bug] Running `bash update.sh` not fetching new icons/version.

### ISSUE THREAD

**Issue by mkaulfers** [iconoir-icons/iconoir-swift#9]
The following error is output by terminal when running the script that auto-generates the new code & fetches the icons. 

```
cp: temp_icons/icons/*.svg: No such file or directory
sed: Sources/Iconoir/Assets.xcassets/*.imageset/*.svg: No such file or directory
Processed *
```

**Comment by mkaulfers** [comment]
@sammarks has anything changed recently that might cause this? Had directory structure changed in the main repository?

**Comment by YoRolling** [comment]
[v6.11.0](https://github.com/iconoir-icons/iconoir/tree/03a415b18e8651b0ef085a02fce61fedc4cf5d4c/icons) vs [v7.0.0](https://github.com/iconoir-icons/iconoir/tree/d30af45b0df2ca43f2010672117baf9805ec62fb/icons) ,see the `icons` folder ，since `v7.0.0`， `icons` folder has some sub-folders cause we has different style icons `regular`+ `solid`,so the `update.sh` failed.


Maybe we should handle this changes,and upgrade the build result for SPM.

**Comment by mkaulfers** [comment]
Ahh that's good to know. I'll take a gander tomorrow and see if I can get it updated.
